$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: modeltraning-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: conda.yml
description: Environment created from a Docker image plus Conda environment.