$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: weather-prediction-deployment
endpoint_name: weather-prediction
model: azureml:WeatherPrediction-Model@latest
app_insights_enabled: true
code_configuration:
  code: ./onlinescoring
  scoring_script: score.py
environment: azureml:modeltraning-env:9
instance_type: Standard_DS2_v2
instance_count: 1
resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi